version: '3.8'

services:
  #Сервис PHP
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      DB_HOST: 'mysql'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    networks:
      - app-network
    volumes:
      - laravel-storage:/var/www/html/storage
  # Сервис веб-сервера
  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - '${APP_PORT:-80}:80'
    networks:
      - app-network

  #Сервис базы данных
  db:
    env_file: .env
    image: mysql:8.2
    container_name: db
    volumes:
      - './mysql:/var/lib/mysql'
    restart: unless-stopped
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
     - "3306:3306"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  laravel-storage:
    driver: local