version: '3.8'

services:
  #Сервис PHP
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: app
    restart: unless-stopped
    tty: true
    command: >
      bash -c "php artisan migrate --seed --env=testing"
    environment:
      DB_HOST: 'mysql'
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    networks:
      - app-network
    volumes:
      - laravel-storage:/var/www/html/storage
  # Сервис веб-сервера
  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - '${APP_PORT:-80}:80'
    networks:
      - app-network

  #Сервис базы данных
  db:
    env_file: .env
    image: mysql:8.2
    container_name: db
    volumes:
      - './mysql/main:/var/lib/mysql'
    restart: unless-stopped
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
     - "3306:3306"
    networks:
      - app-network
  # Сервис тестовой базды данных
  test_db:
    env_file: .env.testing
    image: mysql:8.2
    container_name: test_db
    volumes:
      - './mysql/test:/var/lib/mysql'
    restart: unless-stopped
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"
    networks:
      - app-network

  # # Служба для инициализации тестовой базы данных
  # test_db_init:
  #   build:
  #     context: .
  #     dockerfile: DockerFile
  #   container_name: test_db_init
  #   depends_on:
  #     - test_db
  #   tty: true
  #   command: >
  #     bash -c "php artisan migrate --seed --env=testing"
  #   networks:
  #     - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  laravel-storage:
    driver: local